# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build MetaPhlAn package

on:
  push:
    branches: [ "3.0"]
  pull_request:
    branches: [ "3.0" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install bowtie2 muscle ncbi-blast+ raxml python-numpy python-scipy
        pip install .
    - name: Test 
      run: |
        metaphlan -v
        strainphlan -h
        extract_markers.py -h
        merge_metaphlan_tables.py -h
        read_fastx.py -h
        add_metadata_tree.py -h
        plot_tree_graphlan.py -h
        sample2markers.py -h
        strain_transmission.py -h
